"""Update file schema

Revision ID: 20a55387f845
Revises: 365a563a28a2
Create Date: 2024-09-05 11:22:35.334034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a55387f845'
down_revision: Union[str, None] = '365a563a28a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('files', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'token_count')
    op.drop_column('files', 'size')
    op.drop_column('files', 'mime_type')
    # ### end Alembic commands ###
