"""Increase message id length to 36

Revision ID: 281b0c48b884
Revises: 42c5b45076d5
Create Date: 2024-07-07 19:40:05.120155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281b0c48b884'
down_revision: Union[str, None] = '42c5b45076d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
