"""Update thread schema

Revision ID: 365a563a28a2
Revises: cc826dd3a764
Create Date: 2024-09-05 10:26:33.286201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365a563a28a2'
down_revision: Union[str, None] = 'cc826dd3a764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'is_active')
    # ### end Alembic commands ###
