"""Description of changes

Revision ID: 94b38049cb69
Revises: 4a832ce740b9
Create Date: 2024-09-09 12:53:17.598533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b38049cb69'
down_revision: Union[str, None] = '4a832ce740b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_user_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_message_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_thread_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_thread_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('threads_user_id_fkey', 'threads', type_='foreignkey')
    op.create_foreign_key(None, 'threads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.create_foreign_key('threads_user_id_fkey', 'threads', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_thread_id_fkey', 'messages', 'threads', ['thread_id'], ['id'])
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key('files_thread_id_fkey', 'files', 'threads', ['thread_id'], ['id'])
    op.create_foreign_key('files_message_id_fkey', 'files', 'messages', ['message_id'], ['id'])
    op.create_foreign_key('files_user_id_fkey', 'files', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
