"""Add files relationship to Message model

Revision ID: b748e321a321
Revises: c6d40fa16e3f
Create Date: 2024-09-08 18:00:29.222586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b748e321a321'
down_revision: Union[str, None] = 'c6d40fa16e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('message_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'files', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'message_id')
    # ### end Alembic commands ###
