"""Change thread_id and id to String(32)

Revision ID: c008f28fbbad
Revises: f45b091c7706
Create Date: 2024-06-28 12:08:04.153441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c008f28fbbad'
down_revision: Union[str, None] = 'f45b091c7706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('messages', 'thread_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('threads', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('threads_id_seq'::regclass)"))
    op.drop_column('threads', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('threads', 'id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('threads_id_seq'::regclass)"))
    op.alter_column('messages', 'thread_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('messages', 'feedback')
    # ### end Alembic commands ###
