"""Update Thread schema

Revision ID: c6d40fa16e3f
Revises: 863a9005e753
Create Date: 2024-09-08 17:21:32.246643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d40fa16e3f'
down_revision: Union[str, None] = '863a9005e753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'title')
    # ### end Alembic commands ###
