"""change feedback column on messages table to text

Revision ID: cc826dd3a764
Revises: 281b0c48b884
Create Date: 2024-07-09 13:48:36.454314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc826dd3a764'
down_revision: Union[str, None] = '281b0c48b884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'feedback',
               existing_type=sa.BOOLEAN(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'feedback',
               existing_type=sa.Text(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
