name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Trigger deployment
      run: |
        curl -X POST \
             -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \ # noqa: unknown-context
             https://your-macos-machine-address/deploy